{% set name = "bayeswave" %}
{% set version = "1.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.xz
  sha256: e0ee347b6ed4f8cc1ffd97ffb865cbb0f20d771e198933ccd60f534a0f20c782

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.12.0
    - make
    - pkg-config
  host:
    - fftw * nompi*
    - gsl
    - liblal
    - liblalframe
    - liblalinference
    - liblalsimulation
  run:
    - fftw
    - gsl
    - liblal
    - liblalframe
    - liblalinference
    - liblalsimulation

test:
  requires:
    - pkg-config
  source_files:
    - test/test-bayeswave.sh
  commands:
    # run integration tests
    - bash -ex test/test-bayeswave.sh
    # check executables
    - BayesWave --help
    - BayesWaveCleanFrame --help
    - BayesWaveFpeak --help
    - BayesWavePost --help
    # sanity check pkg-config file
    - pkg-config --print-errors --exact-version {{ version }} bayeswave

outputs:
  - name: bayeswave

  - name: bayeswaveutils
    script: build-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      skip_compile_pyc:
        - bin/*.py
    requirements:
      build:
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
      host:
        - pip
        - python
        - setuptools
      run:
        - astropy
        - gwpy
        - healpy
        - lalapps
        - ligo-gracedb
        - ligo-segments
        - ligo.skymap
        - lscsoft-glue
        - matplotlib-base
        - numpy
        - python
        - python-lal
        - python-lalframe
        - python-lalsimulation
        - python-ligo-lw
        - scipy
        - setuptools
      run_constrained:
        # the last version of ligo.skymap supported on python 3.7
        # isn't compatible with python-ligo-lw >=1.8.0
        - python-ligo-lw <1.8.0  # [py<38]
    test:
      requires:
        - pip
      imports:
        - bayeswave_pipe
        - bayeswave_plot
      commands:
        - python -m pip check
        - bayeswave_pipe --help
    about:
      home: https://git.ligo.org/lscsoft/{{ name }}
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: LICENSE
      summary: Python utilities for BayesWave
      description: |
        A Bayesian algorithm designed to robustly distinguish gravitational
        wave signals from noise and instrumental glitches without relying
        on any prior assumptions of waveform morphology.
        BayesWave produces posterior probability distributions directly on
        gravitational wave signals and instrumental glitches, allowing robust,
        morphology-independent waveform reconstruction.

about:
  home: https://git.ligo.org/lscsoft/{{ name }}/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Bayesian Inference for Gravitational Wave Bursts and Instrument Glitches
  description: |
    A Bayesian algorithm designed to robustly distinguish gravitational wave
    signals from noise and instrumental glitches without relying on any prior
    assumptions of waveform morphology.
    BayesWave produces posterior probability distributions directly on
    gravitational wave signals and instrumental glitches, allowing robust,
    morphology-independent waveform reconstruction.

extra:
  recipe-maintainers:
    - astroclark
    - duncanmmacleod
    - sophiehourihane
