{% set name = "bayeswave" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-v{{ version }}.tar.gz
  sha256: 0c623103b667d00f3cd1234643afcaa48a4f873b87ef0d1238f25832165d05c1
  patches:
    - python3.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - fftw
    - gsl
    - libframe
    - metaio
    - lal
    - lalframe
    - lalinference
    - lalinspiral
    - lalpulsar
    - lalmetaio
    - lalsimulation
  run:
    - fftw
    - gsl
    - libframe
    - metaio
    - lal
    - lalframe
    - lalinference
    - lalinspiral
    - lalpulsar
    - lalmetaio
    - lalsimulation

test:
  source_files:
    - test/test-bayeswave.sh
  commands:
    # run tests
    - bash -ex test/test-bayeswave.sh

    # check scripts
    - BayesWave --help
    - BayesWaveCleanFrame --help
    - BayesWavePost --help
    - BayesWaveToLALPSD --help

outputs:
  - name: bayeswave

  - name: bayeswaveutils
    script: install-python.sh
    build:
      skip: true  # [py<36]
      skip_compile_pyc:
        - bin/*.py
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - healpy
        - lalapps
        - ligo.skymap
        - lscsoft-glue
        - matplotlib-base
        - numpy
        - python-lal
        - python-lalinference
        - setuptools
    test:
      imports:
        - bayeswave_pipe
        - bayeswave_plot
      commands:
        - bayeswave_pipe --help
        - megasky.py --help
    about:
      home: https://git.ligo.org/lscsoft/{{ name }}
      license: GPLv2
      license_family: GPL
      license_file: LICENSE
      summary: Bayesian Inference for Gravitational Wave Bursts and Instrument Glitches
      description: |
        A Bayesian algorithm designed to robustly distinguish gravitational
        wave signals from noise and instrumental glitches without relying
        on any prior assumptions of waveform morphology.
        BayesWave produces posterior probability distributions directly on
        gravitational wave signals and instrumental glitches, allowing robust,
        morphology-independent waveform reconstruction.

about:
  home: https://git.ligo.org/lscsoft/{{ name }}/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: Bayesian Inference for Gravitational Wave Bursts and Instrument Glitches
  description: |
    A Bayesian algorithm designed to robustly distinguish gravitational wave
    signals from noise and instrumental glitches without relying on any prior
    assumptions of waveform morphology.
    BayesWave produces posterior probability distributions directly on
    gravitational wave signals and instrumental glitches, allowing robust,
    morphology-independent waveform reconstruction.

extra:
  recipe-maintainers:
    - astroclark
    - duncanmmacleod
