travis:
  secure:
    BINSTAR_TOKEN: vzc19qNKfFDH8JGAinR89WlnIOL0QDw37Ebz7kDNPPMaMlGyatnzg90p0zcf9RbNa92r/1jxwB5BbBcgj2hPWY0gGtRojMpYXiqNR4zqT8dDE6aH2bkaGYnNH7/VPQvpQr231xQ7gzscJay4P58PlOzlfs5++nGHuajQDNqm52+J3/svJ/UipH3jbRdCyMh8t/yZR2jZDknQjVHUDLROtRRt6qHjRnDlT5bAVnkMlIAt/ZT5YC9IycWu8aUqJOdLadytmNhvg/xrq/6UYbICHV7yS6+nP7RZQ9A02YnQBvOk7gQkULGv+IO/Qv7StA4y9Qhqt2ElOOfbLbO/xh5jqD/dYPRrB8V5XMdtXsFSkPkfuFCTFMi/BCxx+GTPJdlmkAeRBXqyFWlXgbHbivItF/ab67BqKwGi36w3DZ/f3i/YBHlr7ALs04V5124Pg3w+UetBu47ssYQKtyGbO9NaAx4ePVDpeOl2KWZ6DLJA+8PqRV5GIzYCQXJm4AwPmPK7x1FGCVs4yuicELObLgPnx3q1PIqHDunbgk7dL9IzmnyBEVEI4gBhqNBukoUFue3+cgm+VHM8JMf5FSLEiOpS80gC3j4GwYJJ3fzmhXdJPOEqA4JY5CWkBa1YgdxukuWiI/dW+2a3M888axCEHpsXNiYkcTtyUiDnSQ2UuxNRrBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
